### ISSUE TITLE
Updated unRAID to 6.10.3 Traktarr docker no longer runs

### ISSUE THREAD

**Issue by Saorn** [elmerfdz/docker-traktarr#21]
I've deleted the configs and the docker itself and done clean installs several times and I keep seeing this in the log and the app no longer runs.

From https://github.com/l3uddz/traktarr
 * branch            master     -> FETCH_HEAD
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xxbr80_j/backoff_c1e5e98be2c74c0098cfd4f3a45a1b81/setup.py", line 34, in <module>
          core.setup(name='backoff',
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 139, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 477, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 275, in __init__
          self.finalize_options()
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 899, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/usr/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "traktarr.py", line 7, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by Saorn** [comment]
Docker updated last night and now the issue is gone, thank you!
